const mongoose = require('mongoose');
const reviewSchema = new mongoose.Schema({
    userprofile:String,
    username:String,
    content:String,
    reviewdate:String,
    reviewmonth:String,
    reviewyear:String,
    like:Boolean,
    dislike:Boolean,
    likecount:Number,
    date: { type: Date, default: Date.now },
})
const docSchema = new mongoose.Schema({
  name: String,
  email: String,
  profession: String,
  age: Number,
  docid: String,
  docpassword: String,
  isActive: Boolean,
  profile:String,
  about:String,
  review:[reviewSchema],
  c1:String,
  c2:String,
  c3:String,
  c4:String,
  c5:String,
  patientAt1: {
    time:Number,
    available: Boolean,
    timeout:Boolean,
    name: String,
    age:Number,
    gender:String,
    mobileno:String,
    usid:String,
    a1:String,
    a2:String,
    a3:String,
  },
  patientAt2: {
    time:Number,
    available: Boolean,
    timeout:Boolean,
    name: String,
    age:Number,
    gender:String,
    mobileno:String,
    usid:String,
    a1:String,
    a2:String,
    a3:String,
  },
  patientAt3: {
    time:Number,
    available: Boolean,
    timeout:Boolean,
    name: String,
    age:Number,
    gender:String,
    mobileno:String,
    usid:String,
    a1:String,
    a2:String,
    a3:String,
  },
});

const Doctermodel = mongoose.model('Docter', docSchema);
module.exports = Doctermodel